version: "3.8"
services:
  demoapi:
    image: demo:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
     - "5081:8080"
     - "5444:443"
    volumes:
      - "./aspnet:/root/.aspnet/https:ro"
      - "./aspnet:/root/.microsoft/usersecrets:ro"
      - "./Logs:/App/Logs"

# volumes:
#   mssql_log:
# networks:
#   default:
#     external: true
#     name: reverse-proxy
